# Generated by Django 6.0.6 on 2026-07-07 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0029_add_search_title_to_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "field",
                    models.CharField(
                        choices=[("title", "Title"), ("summary", "Summary")],
                        help_text="The Game field this suggestion proposes a new Polish value for.",
                        max_length=10,
                        verbose_name="field",
                    ),
                ),
                (
                    "current_value",
                    models.TextField(
                        blank=True,
                        help_text="A snapshot of the field's value at the time this suggestion was submitted.",
                        verbose_name="current value",
                    ),
                ),
                (
                    "proposed_value",
                    models.TextField(
                        blank=True,
                        help_text="The proposed new Polish value for the field.",
                        verbose_name="proposed value",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        help_text="The current lifecycle state of this suggestion.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True, verbose_name="submitted at")),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time this suggestion was accepted or rejected.",
                        null=True,
                        verbose_name="reviewed at",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional reason given by the admin when rejecting this suggestion.",
                        max_length=500,
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="The game this suggestion targets.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_suggestions",
                        to="games.game",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who accepted or rejected this suggestion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_translation_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="The user who submitted this suggestion.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "translation suggestion",
                "verbose_name_plural": "translation suggestions",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("game", "field", "submitted_by"),
                        name="unique_pending_suggestion_per_user_game_field",
                    )
                ],
            },
        ),
    ]
