# Generated by Django 6.0.6 on 2026-07-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0030_translationsuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamereview",
            name="is_moderated",
            field=models.BooleanField(
                default=False,
                help_text="Whether an accepted Report has flagged this review's text for masking.",
                verbose_name="is moderated",
            ),
        ),
    ]
