# Generated by Django 6.0.6 on 2026-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0032_gamelist_is_moderated"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationsuggestion",
            name="is_moderated",
            field=models.BooleanField(
                default=False,
                help_text="Whether an accepted Report has flagged this suggestion's proposed_value for masking.",
                verbose_name="is moderated",
            ),
        ),
    ]
