# Generated by Django 6.1 on 2026-08-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0033_translationsuggestion_is_moderated"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamereview",
            name="recommendation",
            field=models.CharField(
                choices=[
                    ("recommended", "Recommended"),
                    ("not_recommended", "Not Recommended"),
                    ("undecided", "Undecided"),
                ],
                default="undecided",
                help_text="Whether the reviewer recommends this game (Recommended, Not Recommended, Undecided).",
                max_length=16,
                verbose_name="recommendation",
            ),
            preserve_default=False,
        ),
    ]
