# Generated by Django 6.1 on 2026-08-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0034_gamereview_recommendation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamefollow",
            name="user",
            field=models.ForeignKey(
                help_text="The user following the game.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamereview",
            name="user",
            field=models.ForeignKey(
                help_text="The user who wrote the review.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
