# Generated by Django 6.0.6 on 2026-07-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("friendship", "Friendship"),
                    ("game_release", "Game Release"),
                    ("translation", "Translation Suggestion"),
                    ("moderation", "Moderation"),
                ],
                default="system",
                help_text="The category of the notification.",
                max_length=20,
                verbose_name="category",
            ),
        ),
    ]
