# Generated by Django 6.1 on 2026-08-25 20:52

import re
import unicodedata
from typing import Any

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

GAME_MEDIA_INITIAL_DATA = [
    {"name": "Steam"},
    {"name": "GOG"},
    {"name": "Epic Games Store"},
    {"name": "PlayStation Store"},
    {"name": "Physical copy"},
]


def populate_game_media(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """This function populates the initial values for the GameMedia model.

    The historical model returned by ``apps.get_model`` bypasses modeltranslation's runtime
    field-routing, so ``name_en`` (the field actually read through the translated ``name``
    accessor) must be set explicitly alongside the legacy ``name`` column - setting only
    ``name`` leaves ``name_en`` NULL for every seeded row.
    """
    game_media_model = apps.get_model("games", "GameMedia")
    game_media_model.objects.bulk_create(
        [game_media_model(name=data["name"], name_en=data["name"]) for data in GAME_MEDIA_INITIAL_DATA],
    )


def remove_initial_game_media(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """This function removes the initial values for the GameMedia model."""
    game_media_model = apps.get_model("games", "GameMedia")
    game_media_model.objects.filter(name_en__in=[data["name"] for data in GAME_MEDIA_INITIAL_DATA]).delete()


def backfill_search_title(apps: Any, _schema_editor: Any) -> None:
    def normalize(value: str) -> str:
        value = unicodedata.normalize("NFD", value)
        value = "".join(c for c in value if unicodedata.category(c) != "Mn")
        value = value.lower()
        value = re.sub(r"[^a-z0-9\s]", " ", value)
        return re.sub(r"\s+", " ", value).strip()

    game_model = apps.get_model("games", "Game")
    batch = []
    for game in game_model.objects.iterator(chunk_size=500):
        parts = {normalize(t) for t in (game.title_en or "", game.title_pl or "") if t}
        game.search_title = " ".join(sorted(parts))
        batch.append(game)
        if len(batch) >= 500:
            game_model.objects.bulk_update(batch, ["search_title"])
            batch.clear()
    if batch:
        game_model.objects.bulk_update(batch, ["search_title"])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("company_logo_id", models.CharField(blank=True, max_length=255, verbose_name="company logo id")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
            ],
            options={
                "verbose_name": "genre",
                "verbose_name_plural": "genres",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("abbreviation", models.CharField(blank=True, max_length=255, verbose_name="abbreviation")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
            ],
            options={
                "verbose_name": "platform",
                "verbose_name_plural": "platforms",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("abbreviation__gt", ""), ("abbreviation__isnull", False)),
                        fields=("abbreviation",),
                        name="unique_abbreviation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, unique=True, verbose_name="title")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                ("release_date", models.DateField(blank=True, null=True, verbose_name="release date")),
                ("cover_image_id", models.CharField(blank=True, max_length=255, verbose_name="cover image id")),
                ("summary", models.TextField(blank=True, max_length=2000, verbose_name="summary")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_developed",
                        to="games.company",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_published",
                        to="games.company",
                    ),
                ),
                ("genres", models.ManyToManyField(related_name="games", to="games.genre")),
                ("platforms", models.ManyToManyField(related_name="games", to="games.platform")),
            ],
            options={
                "verbose_name": "game",
                "verbose_name_plural": "games",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameFollow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="follow_list", to="games.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games_followed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "game follow",
                "verbose_name_plural": "games followed",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("game", "user"), name="unique_game_user_in_game_follow")
                ],
            },
        ),
        migrations.CreateModel(
            name="GameReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                ("review", models.TextField(blank=True, max_length=1000, verbose_name="review")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="reviews", to="games.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="reviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "game review",
                "verbose_name_plural": "games reviews",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("game", "user"), name="unique_game_user_in_game_review")
                ],
            },
        ),
        migrations.CreateModel(
            name="GameMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
            ],
            options={
                "verbose_name": "game_media",
                "verbose_name_plural": "game_medias",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="score",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("C", "Completed"),
                            ("PTP", "Plan to play"),
                            ("P", "Playing"),
                            ("D", "Dropped"),
                            ("OH", "On hold"),
                        ],
                        max_length=3,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="game_lists", to="games.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("owned_on", models.ManyToManyField(related_name="game_lists", to="games.gamemedia")),
            ],
            options={
                "verbose_name": "game list",
                "verbose_name_plural": "game lists",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [models.UniqueConstraint(fields=("game", "user"), name="unique_game_user_in_game_list")],
            },
        ),
        migrations.AlterModelOptions(
            name="gamemedia",
            options={"ordering": ("id",), "verbose_name": "game media", "verbose_name_plural": "game medias"},
        ),
        migrations.AlterModelOptions(
            name="gamefollow",
            options={"ordering": ("id",), "verbose_name": "game follow", "verbose_name_plural": "games follows"},
        ),
        migrations.AddField(
            model_name="game",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genre",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platform",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(help_text="The game's title.", max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="creation time"),
        ),
        migrations.CreateModel(
            name="GameEngine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="The game engine's name.", max_length=255, verbose_name="name")),
                (
                    "igdb_id",
                    models.PositiveIntegerField(
                        help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
                    ),
                ),
                (
                    "igdb_updated_at",
                    models.DateTimeField(
                        help_text="Timestamp of the last synchronisation with IGDB.",
                        verbose_name="igdb last updated at",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The game engine's name.", max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_pl",
                    models.CharField(
                        help_text="The game engine's name.", max_length=255, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "game engine",
                "verbose_name_plural": "game engines",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameMode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "igdb_id",
                    models.PositiveIntegerField(
                        help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
                    ),
                ),
                (
                    "igdb_updated_at",
                    models.DateTimeField(
                        help_text="Timestamp of the last synchronisation with IGDB.",
                        verbose_name="igdb last updated at",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The display name of this record.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_pl",
                    models.CharField(
                        help_text="The display name of this record.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "game mode",
                "verbose_name_plural": "game modes",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "igdb_id",
                    models.PositiveIntegerField(
                        help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
                    ),
                ),
                (
                    "igdb_updated_at",
                    models.DateTimeField(
                        help_text="Timestamp of the last synchronisation with IGDB.",
                        verbose_name="igdb last updated at",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="The release status name (e.g. Released, Alpha, Early Access).",
                        max_length=255,
                        unique=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_en",
                    models.CharField(
                        help_text="The release status name (e.g. Released, Alpha, Early Access).",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_pl",
                    models.CharField(
                        help_text="The release status name (e.g. Released, Alpha, Early Access).",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "verbose_name": "game status",
                "verbose_name_plural": "game statuses",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "igdb_id",
                    models.PositiveIntegerField(
                        help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
                    ),
                ),
                (
                    "igdb_updated_at",
                    models.DateTimeField(
                        help_text="Timestamp of the last synchronisation with IGDB.",
                        verbose_name="igdb last updated at",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="The game type name (e.g. Main Game, DLC, Expansion).",
                        max_length=255,
                        unique=True,
                        verbose_name="type",
                    ),
                ),
                (
                    "type_en",
                    models.CharField(
                        help_text="The game type name (e.g. Main Game, DLC, Expansion).",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="type",
                    ),
                ),
                (
                    "type_pl",
                    models.CharField(
                        help_text="The game type name (e.g. Main Game, DLC, Expansion).",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "game type",
                "verbose_name_plural": "game types",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerPerspective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "igdb_id",
                    models.PositiveIntegerField(
                        help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
                    ),
                ),
                (
                    "igdb_updated_at",
                    models.DateTimeField(
                        help_text="Timestamp of the last synchronisation with IGDB.",
                        verbose_name="igdb last updated at",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The display name of this record.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_pl",
                    models.CharField(
                        help_text="The display name of this record.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "player perspective",
                "verbose_name_plural": "player perspectives",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="game",
            name="bundles",
            field=models.ManyToManyField(blank=True, related_name="bundled_in", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="dlcs",
            field=models.ManyToManyField(blank=True, related_name="dlc_of", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="expanded_games",
            field=models.ManyToManyField(blank=True, related_name="expanded_by", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="expansions",
            field=models.ManyToManyField(blank=True, related_name="expansion_of", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="forks",
            field=models.ManyToManyField(blank=True, related_name="fork_of", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="parent_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_games",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="ports",
            field=models.ManyToManyField(blank=True, related_name="port_of", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="screenshots",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="IGDB screenshot IDs for this game.",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="standalone_expansions",
            field=models.ManyToManyField(blank=True, related_name="standalone_expansion_of", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="game_engines",
            field=models.ManyToManyField(
                blank=True,
                help_text="Game engines used to build this game.",
                related_name="games",
                to="games.gameengine",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_modes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Supported game modes (single-player, multiplayer, co-op, etc.).",
                related_name="games",
                to="games.gamemode",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_status",
            field=models.ForeignKey(
                blank=True,
                help_text="The current release status of the game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="games.gamestatus",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The game type (Main Game, DLC, Expansion, etc.).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="games.gametype",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player_perspectives",
            field=models.ManyToManyField(
                blank=True,
                help_text="Supported player perspectives (first-person, third-person, etc.).",
                related_name="games",
                to="games.playerperspective",
            ),
        ),
        migrations.CreateModel(
            name="ExternalGameSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "igdb_id",
                    models.PositiveIntegerField(
                        help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
                    ),
                ),
                (
                    "igdb_updated_at",
                    models.DateTimeField(
                        help_text="Timestamp of the last synchronisation with IGDB.",
                        verbose_name="igdb last updated at",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The display name of this record.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_pl",
                    models.CharField(
                        help_text="The display name of this record.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "external game source",
                "verbose_name_plural": "external game sources",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalGame",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "igdb_id",
                    models.PositiveIntegerField(
                        help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
                    ),
                ),
                (
                    "igdb_updated_at",
                    models.DateTimeField(
                        help_text="Timestamp of the last synchronisation with IGDB.",
                        verbose_name="igdb last updated at",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="The game's identifier on the external platform.",
                        max_length=255,
                        verbose_name="external id",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="A direct link to the game on the external platform.",
                        max_length=1024,
                        verbose_name="url",
                    ),
                ),
                (
                    "external_game_source",
                    models.ForeignKey(
                        help_text="The external platform where this game is listed (e.g. Steam, GOG).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_games",
                        to="games.externalgamesource",
                    ),
                ),
            ],
            options={
                "verbose_name": "external game",
                "verbose_name_plural": "external games",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="game",
            name="external_games",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to external platforms where this game is available.",
                related_name="games",
                to="games.externalgame",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-safe identifier, auto-generated from the English title.",
                max_length=512,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="summary_en",
            field=models.TextField(
                blank=True,
                help_text="A short description or synopsis of the game.",
                max_length=2000,
                null=True,
                verbose_name="summary",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="summary_pl",
            field=models.TextField(
                blank=True,
                help_text="A short description or synopsis of the game.",
                max_length=2000,
                null=True,
                verbose_name="summary",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="title_en",
            field=models.CharField(help_text="The game's title.", max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="game",
            name="title_pl",
            field=models.CharField(help_text="The game's title.", max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="gamemedia",
            name="name_en",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="gamemedia",
            name="name_pl",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="genre",
            name="name_en",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="genre",
            name="name_pl",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="platform",
            name="name_en",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="platform",
            name="name_pl",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_logo_id",
            field=models.CharField(
                blank=True,
                help_text="The IGDB logo ID used to construct the company logo image URL.",
                max_length=255,
                verbose_name="company logo id",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(help_text="The company's name.", max_length=255, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="company",
            name="name_en",
            field=models.CharField(help_text="The company's name.", max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="company",
            name="name_pl",
            field=models.CharField(help_text="The company's name.", max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-safe identifier, auto-generated from the company name.",
                max_length=512,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="bundles",
            field=models.ManyToManyField(
                blank=True, help_text="Bundles that include this game.", related_name="bundled_in", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="cover_image_id",
            field=models.CharField(
                blank=True,
                help_text="The IGDB cover image ID used to construct the cover image URL.",
                max_length=255,
                verbose_name="cover image id",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                help_text="The company that developed this game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_developed",
                to="games.company",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="dlcs",
            field=models.ManyToManyField(
                blank=True, help_text="DLC additions for this game.", related_name="dlc_of", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="expanded_games",
            field=models.ManyToManyField(
                blank=True, help_text="Games expanded by this game.", related_name="expanded_by", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="expansions",
            field=models.ManyToManyField(
                blank=True, help_text="Expansions of this game.", related_name="expansion_of", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="forks",
            field=models.ManyToManyField(
                blank=True, help_text="Fork versions derived from this game.", related_name="fork_of", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(
                help_text="Genres this game belongs to.", related_name="games", to="games.genre"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="parent_game",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent game this record is a DLC, expansion, or port of.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_games",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(
                help_text="Platforms this game is available on.", related_name="games", to="games.platform"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="ports",
            field=models.ManyToManyField(
                blank=True, help_text="Platform ports of this game.", related_name="port_of", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                help_text="The company that published this game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_published",
                to="games.company",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateField(
                blank=True, help_text="The worldwide release date of the game.", null=True, verbose_name="release date"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="standalone_expansions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Standalone expansions of this game.",
                related_name="standalone_expansion_of",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="A short description or synopsis of the game.",
                max_length=2000,
                verbose_name="summary",
            ),
        ),
        migrations.AlterField(
            model_name="gamefollow",
            name="game",
            field=models.ForeignKey(
                help_text="The game being followed.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="follow_list",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamefollow",
            name="user",
            field=models.ForeignKey(
                help_text="The user following the game.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games_followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="completed_at",
            field=models.DateField(
                blank=True, help_text="The date the user completed this game.", null=True, verbose_name="completed at"
            ),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional personal notes about this game.",
                max_length=200,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="game",
            field=models.ForeignKey(
                help_text="The game this list entry refers to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_lists",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="owned_on",
            field=models.ManyToManyField(
                help_text="The media formats on which the user owns this game.",
                related_name="game_lists",
                to="games.gamemedia",
            ),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="playtime",
            field=models.PositiveIntegerField(
                blank=True, help_text="The number of minutes played.", null=True, verbose_name="playtime"
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The user's score for this game, between 1 and 10.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="score",
            ),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="started_at",
            field=models.DateField(
                blank=True,
                help_text="The date the user started playing this game.",
                null=True,
                verbose_name="started at",
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="status",
            field=models.CharField(
                choices=[
                    ("C", "Completed"),
                    ("PTP", "Plan to play"),
                    ("P", "Playing"),
                    ("D", "Dropped"),
                    ("OH", "On hold"),
                ],
                help_text="The user's current play status (Completed, Plan to Play, Playing, Dropped, On Hold).",
                max_length=3,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this game list entry.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamemedia",
            name="name",
            field=models.CharField(
                help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.RunPython(
            code=populate_game_media,
            reverse_code=remove_initial_game_media,
        ),
        migrations.AlterField(
            model_name="gamereview",
            name="game",
            field=models.ForeignKey(
                help_text="The game being reviewed.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamereview",
            name="review",
            field=models.TextField(blank=True, help_text="The review text.", max_length=1000, verbose_name="review"),
        ),
        migrations.AlterField(
            model_name="gamereview",
            name="user",
            field=models.ForeignKey(
                help_text="The user who wrote the review.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GameStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "score_sum",
                    models.BigIntegerField(
                        default=0,
                        help_text="The sum of all user scores, used for average calculation.",
                        verbose_name="score sum",
                    ),
                ),
                (
                    "score_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of users who have scored this game.",
                        verbose_name="score count",
                    ),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=0,
                        help_text="The computed average score across all user ratings.",
                        max_digits=4,
                        verbose_name="average score",
                    ),
                ),
                (
                    "members_count",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="The number of users who have this game in their game list.",
                        verbose_name="members count",
                    ),
                ),
                (
                    "popularity",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="The game's popularity rank, updated periodically by a background task.",
                        null=True,
                        verbose_name="popularity",
                    ),
                ),
                (
                    "rank_position",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="The game's position in the all-time ranking, updated periodically.",
                        null=True,
                        verbose_name="rank position",
                    ),
                ),
                (
                    "game",
                    models.OneToOneField(
                        help_text="The game this statistics record belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "game stats",
                "verbose_name_plural": "game stats",
            },
        ),
        migrations.AlterField(
            model_name="genre",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                help_text="A short abbreviation for the platform name (e.g. PS5, PC).",
                max_length=255,
                verbose_name="abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(
                help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
            ),
        ),
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddField(
            model_name="game",
            name="search_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Normalized title used for fuzzy search (lowercase, no diacritics, no special chars).",
                max_length=511,
                verbose_name="search title",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="externalgame",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="externalgamesource",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gameengine",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gamemode",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gamestatus",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gametype",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="playerperspective",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_title"], name="games_game_search_title_gin", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.RunPython(
            code=backfill_search_title,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="gamereview",
            name="is_moderated",
            field=models.BooleanField(
                default=False,
                help_text="Whether an accepted Report has flagged this review's text for masking.",
                verbose_name="is moderated",
            ),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="is_moderated",
            field=models.BooleanField(
                default=False,
                help_text="Whether an accepted Report has flagged this note's text for masking.",
                verbose_name="is moderated",
            ),
        ),
        migrations.CreateModel(
            name="TranslationSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "field",
                    models.CharField(
                        choices=[("title", "Title"), ("summary", "Summary")],
                        help_text="The Game field this suggestion proposes a new Polish value for.",
                        max_length=10,
                        verbose_name="field",
                    ),
                ),
                (
                    "current_value",
                    models.TextField(
                        blank=True,
                        help_text="A snapshot of the field's value at the time this suggestion was submitted.",
                        verbose_name="current value",
                    ),
                ),
                (
                    "proposed_value",
                    models.TextField(
                        blank=True,
                        help_text="The proposed new Polish value for the field.",
                        verbose_name="proposed value",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        help_text="The current lifecycle state of this suggestion.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True, verbose_name="submitted at")),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time this suggestion was accepted or rejected.",
                        null=True,
                        verbose_name="reviewed at",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional reason given by the admin when rejecting this suggestion.",
                        max_length=500,
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="The game this suggestion targets.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_suggestions",
                        to="games.game",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who accepted or rejected this suggestion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_translation_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="The user who submitted this suggestion.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "is_moderated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether an accepted Report has flagged this suggestion's proposed_value for masking.",
                        verbose_name="is moderated",
                    ),
                ),
            ],
            options={
                "verbose_name": "translation suggestion",
                "verbose_name_plural": "translation suggestions",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("game", "field", "submitted_by"),
                        name="unique_pending_suggestion_per_user_game_field",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="gamereview",
            name="recommendation",
            field=models.CharField(
                choices=[
                    ("recommended", "Recommended"),
                    ("not_recommended", "Not Recommended"),
                    ("undecided", "Undecided"),
                ],
                default="undecided",
                help_text="Whether the reviewer recommends this game (Recommended, Not Recommended, Undecided).",
                max_length=16,
                verbose_name="recommendation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gamefollow",
            name="user",
            field=models.ForeignKey(
                help_text="The user following the game.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamereview",
            name="user",
            field=models.ForeignKey(
                help_text="The user who wrote the review.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
