# Generated by Django 6.1 on 2026-09-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelist",
            name="status",
            field=models.CharField(
                choices=[
                    ("C", "Completed"),
                    ("PTP", "Plan to play"),
                    ("P", "Playing"),
                    ("D", "Dropped"),
                    ("OH", "On hold"),
                    ("NP", "Not planned"),
                ],
                help_text="The user's current play status (Completed, Plan to Play, Playing, Dropped, On Hold, Not Planned).",
                max_length=3,
                verbose_name="status",
            ),
        ),
    ]
