# Generated by Django 6.1 on 2026-09-24 00:00

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

GAME_MEDIA_NAME = "Xbox"


def populate_xbox_game_media(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """This function adds the Xbox value for the GameMedia model.

    The historical model returned by ``apps.get_model`` bypasses modeltranslation's runtime
    field-routing, so ``name_en`` (the field actually read through the translated ``name``
    accessor) must be set explicitly alongside the legacy ``name`` column - setting only
    ``name`` leaves ``name_en`` NULL for the seeded row.
    """
    game_media_model = apps.get_model("games", "GameMedia")
    game_media_model.objects.create(name=GAME_MEDIA_NAME, name_en=GAME_MEDIA_NAME)


def remove_xbox_game_media(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """This function removes the Xbox value for the GameMedia model."""
    game_media_model = apps.get_model("games", "GameMedia")
    game_media_model.objects.filter(name_en=GAME_MEDIA_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_gamelist_status"),
    ]

    operations = [
        migrations.RunPython(populate_xbox_game_media, reverse_code=remove_xbox_game_media),
    ]
