# Generated by Django 6.0.6 on 2026-07-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0031_gamereview_is_moderated"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelist",
            name="is_moderated",
            field=models.BooleanField(
                default=False,
                help_text="Whether an accepted Report has flagged this note's text for masking.",
                verbose_name="is moderated",
            ),
        ),
    ]
