services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  app:
    networks:
      - loki
      - shared

  celery_worker:
    networks:
      - loki
      - shared

  celery_beat:
    networks:
      - loki
      - shared

  keycloak_events_consumer:
    networks:
      - loki
      - shared

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"

  loki:
    ports:
      - "3100"

  tempo:
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP

networks:
  shared:
    name: sojusan-apps-shared-network
    external: true
