# Generated by Django 6.1 on 2026-08-25 20:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "email",
                    models.EmailField(
                        help_text="The user's email address. Used as the login credential.",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        help_text="The user's gender. Optional.",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "last_active",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the user's most recent activity. Null if never recorded.",
                        null=True,
                        verbose_name="last active",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-safe identifier for the user profile, auto-generated from the username.",
                        max_length=255,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this user has accumulated 3 warnings, or been banned directly. Distinct from is_active, which gates login.",
                        verbose_name="is banned",
                    ),
                ),
                (
                    "has_moderated_avatar",
                    models.BooleanField(
                        default=False,
                        help_text="Whether an accepted avatar Report hides gravatar_url for literally everyone, including self.",
                        verbose_name="has moderated avatar",
                    ),
                ),
                (
                    "has_moderated_username",
                    models.BooleanField(
                        default=False,
                        help_text="Whether an accepted username Report masks the username for other viewers.",
                        verbose_name="has moderated username",
                    ),
                ),
                (
                    "keycloak_id",
                    models.UUIDField(
                        blank=True,
                        help_text="The 'sub' claim of this user's Keycloak identity. Null for accounts created outside Keycloak.",
                        null=True,
                        unique=True,
                        verbose_name="keycloak id",
                    ),
                ),
                (
                    "ban_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why this user was banned - auto-generated for the warning threshold, admin-supplied for a direct ban.",
                        verbose_name="ban reason",
                    ),
                ),
                (
                    "banned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this user was banned. Null if never banned.",
                        null=True,
                        verbose_name="banned at",
                    ),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who banned this user - automatically, at the 3rd warning, or via a direct ban.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banned_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
