# Generated by Django 6.0.6 on 2026-07-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_is_banned"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_moderated_avatar",
            field=models.BooleanField(
                default=False,
                help_text="Whether an accepted avatar Report hides gravatar_url for literally everyone, including self.",
                verbose_name="has moderated avatar",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="has_moderated_username",
            field=models.BooleanField(
                default=False,
                help_text="Whether an accepted username Report masks the username for other viewers.",
                verbose_name="has moderated username",
            ),
        ),
    ]
