# Generated by Django 6.0.6 on 2026-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_has_moderated_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="keycloak_id",
            field=models.UUIDField(
                blank=True,
                help_text="The 'sub' claim of this user's Keycloak identity. Null for accounts created outside Keycloak.",
                null=True,
                unique=True,
                verbose_name="keycloak id",
            ),
        ),
    ]
