# Generated by Django 6.1 on 2026-08-20 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_keycloak_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ban_reason",
            field=models.TextField(
                blank=True,
                help_text="Why this user was banned - auto-generated for the warning threshold, admin-supplied for a direct ban.",
                verbose_name="ban reason",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="banned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this user was banned. Null if never banned.",
                null=True,
                verbose_name="banned at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="banned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The admin who banned this user - automatically, at the 3rd warning, or via a direct ban.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banned_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user has accumulated 3 warnings, or been banned directly. Distinct from is_active, which gates login.",
                verbose_name="is banned",
            ),
        ),
    ]
