server{
    listen 80;
    server_name gamelist.sojusan.pl;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 308 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name gamelist.sojusan.pl;

    ssl_certificate     /etc/letsencrypt/live/gamelist.sojusan.pl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gamelist.sojusan.pl/privkey.pem;

    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 10M;

    resolver 127.0.0.11;

    # --------------------------------------------------
    # Backend API
    # --------------------------------------------------

    location /api/ {
        proxy_pass http://app:8000;
        include /etc/nginx/proxy.conf;
    }

    # --------------------------------------------------
    # Public version endpoint
    # --------------------------------------------------

    location = /version/ {
        proxy_pass http://app:8000;
        include /etc/nginx/proxy.conf;
    }

    # --------------------------------------------------
    # Prometheus metrics
    # Docker network + VPN only
    # --------------------------------------------------

    location = /prometheus/metrics {
        allow 10.8.0.0/24;
        deny all;

        proxy_pass http://app:8000;
        include /etc/nginx/proxy.conf;
    }

    # --------------------------------------------------
    # Django admin - VPN only
    # --------------------------------------------------

    location /admin/ {
        allow 10.8.0.0/24;
        deny all;

        proxy_pass http://app:8000;
        include /etc/nginx/proxy.conf;
    }

    # --------------------------------------------------
    # Backend static files and media files
    # --------------------------------------------------

    location /static/ {
        alias /opt/game_list/static/;
    }

    location /media/ {
        alias /opt/game_list/media/;
    }

    # --------------------------------------------------
    # Gateway health check
    # --------------------------------------------------

    location = /status {
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # --------------------------------------------------
    # Frontend
    # Everything else goes to frontend nginx
    # --------------------------------------------------

    location / {
        proxy_pass http://frontend:8080;
        include /etc/nginx/proxy.conf;
    }
}
