{
 "title": "GameList",
 "description": "A dashboard for game-list",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Dashboard time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 0 },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "GameList logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"app\"} |= ``"
    }
   ]
  },
  {
   "title": "Users registered per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(users_registered_total[1d])",
     "legendFormat": "new users per day"
    }
   ]
  },
  {
   "title": "Game list entries created per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(game_lists_entries_created_total[1d])",
     "legendFormat": "new game list entries per day"
    }
   ]
  }
 ]
}