# Generated by Django 6.1 on 2026-08-25 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="The name of the collection.", max_length=255, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="An optional description of the collection.",
                        max_length=1000,
                        verbose_name="description",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the collection is marked as a favorite by its owner.",
                        verbose_name="is favorite",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUB", "Public"), ("FRI", "Friends only"), ("PRI", "Private")],
                        default="PRI",
                        help_text="Visibility level: PUBLIC, FRIENDS (friends only), or PRIVATE.",
                        max_length=3,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("S", "Solo"), ("C", "Collaborative")],
                        default="S",
                        help_text="Collection mode: SOLO (single owner) or COLLABORATIVE (multiple contributors).",
                        max_length=1,
                        verbose_name="mode",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users allowed to add and reorder items in COLLABORATIVE collections.",
                        related_name="collaborated_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="collaborators",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The owner of the collection.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("NOR", "Normal"), ("RNK", "Ranking"), ("TIE", "Tier list")],
                        default="NOR",
                        help_text="Collection type: NORMAL, RANK (ordered ranking), or TIER (tier list).",
                        max_length=3,
                        verbose_name="type",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-safe identifier auto-generated from the owner username and collection name.",
                        max_length=512,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "is_moderated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether an accepted Report has flagged this collection's name/description for masking.",
                        verbose_name="is moderated",
                    ),
                ),
            ],
            options={
                "verbose_name": "collection",
                "verbose_name_plural": "collections",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "order",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=10,
                        help_text="Fractional decimal position within the collection. Lower values appear first.",
                        max_digits=20,
                        null=True,
                        verbose_name="order",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S Tier"),
                            ("A", "A Tier"),
                            ("B", "B Tier"),
                            ("C", "C Tier"),
                            ("D", "D Tier"),
                            ("E", "E Tier"),
                            ("F", "F Tier"),
                        ],
                        db_index=True,
                        help_text="Optional tier classification for TIER-type collections (S, A, B, C, D, E, or F).",
                        max_length=1,
                        verbose_name="tier",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes or justification for this item's position in the collection.",
                        max_length=500,
                        verbose_name="description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                (
                    "added_by",
                    models.ForeignKey(
                        help_text="The user who added this item. May be null if the adding user was deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_items_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="added by",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        help_text="The collection this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="collections.collection",
                        verbose_name="collection",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="The game this item represents.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_items",
                        to="games.game",
                        verbose_name="game",
                    ),
                ),
                (
                    "is_moderated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether an accepted Report has flagged this item's note for masking.",
                        verbose_name="is moderated",
                    ),
                ),
            ],
            options={
                "verbose_name": "collection item",
                "verbose_name_plural": "collection items",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [models.UniqueConstraint(fields=("collection", "game"), name="unique_collection_game")],
            },
        ),
    ]
