# Generated by Django 6.1 on 2026-09-21 16:57

from typing import TYPE_CHECKING

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def favorite_flagged_collections_for_owners(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Turn the owner-level `is_favorite` flag into a favorite for the owner of each flagged collection."""
    collection = apps.get_model("collections", "Collection")  # noqa: N806
    collection_favorite = apps.get_model("collections", "CollectionFavorite")  # noqa: N806
    db_alias = schema_editor.connection.alias

    collection_favorite.objects.using(db_alias).bulk_create(
        [
            collection_favorite(collection_id=collection_id, user_id=user_id)
            for collection_id, user_id in collection.objects.using(db_alias)
            .filter(is_favorite=True)  # type: ignore[misc]
            .values_list("id", "user_id")
        ],
        ignore_conflicts=True,
    )


def flag_collections_favorited_by_owners(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Restore the owner-level `is_favorite` flag from the owner's own favorite; other users' favorites are dropped."""
    collection_favorite = apps.get_model("collections", "CollectionFavorite")  # noqa: N806
    collection = apps.get_model("collections", "Collection")  # noqa: N806
    db_alias = schema_editor.connection.alias

    owner_favorited_ids = (
        collection_favorite.objects.using(db_alias)
        .filter(user_id=F("collection__user_id"))
        .values_list("collection_id", flat=True)
    )
    collection.objects.using(db_alias).filter(id__in=owner_favorited_ids).update(is_favorite=True)  # type: ignore[misc]


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                (
                    "collection",
                    models.ForeignKey(
                        help_text="The collection that was favorited.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="collections.collection",
                        verbose_name="collection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who favorited the collection.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "collection favorite",
                "verbose_name_plural": "collection favorites",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("collection", "user"), name="unique_collection_user_favorite")
                ],
            },
        ),
        migrations.RunPython(favorite_flagged_collections_for_owners, flag_collections_favorited_by_owners),
        migrations.RemoveField(
            model_name="collection",
            name="is_favorite",
        ),
    ]
