# Generated by Django 6.0.6 on 2026-07-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0009_alter_collection_is_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_moderated",
            field=models.BooleanField(
                default=False,
                help_text="Whether an accepted Report has flagged this collection's name/description for masking.",
                verbose_name="is moderated",
            ),
        ),
    ]
