# Generated by Django 6.1 on 2026-08-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0011_collectionitem_is_moderated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "S Tier"),
                    ("A", "A Tier"),
                    ("B", "B Tier"),
                    ("C", "C Tier"),
                    ("D", "D Tier"),
                    ("E", "E Tier"),
                    ("F", "F Tier"),
                ],
                db_index=True,
                help_text="Optional tier classification for TIER-type collections (S, A, B, C, D, E, or F).",
                max_length=1,
                verbose_name="tier",
            ),
        ),
    ]
