# Generated by Django 6.0.6 on 2026-07-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0010_collection_is_moderated"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="is_moderated",
            field=models.BooleanField(
                default=False,
                help_text="Whether an accepted Report has flagged this item's note for masking.",
                verbose_name="is moderated",
            ),
        ),
    ]
