# Generated by Django 6.1 on 2026-08-25 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                (
                    "friend",
                    models.ForeignKey(
                        help_text="The other party in the friendship.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_friends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="One party in the friendship.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "friendship",
                "verbose_name_plural": "friendships",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [models.UniqueConstraint(fields=("user", "friend"), name="unique_user_friend")],
            },
        ),
        migrations.CreateModel(
            name="FriendshipRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="An optional personal message accompanying the friendship request.",
                        max_length=100,
                        verbose_name="message",
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the request was rejected, or null if not yet rejected.",
                        null=True,
                        verbose_name="rejection time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="The user who received the friendship request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="The user who sent the friendship request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "friendship request",
                "verbose_name_plural": "friendship requests",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [models.UniqueConstraint(fields=("sender", "receiver"), name="unique_sender_receiver")],
            },
        ),
    ]
