# Generated by Django 6.0.6 on 2026-07-09 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collections", "0009_alter_collection_is_favorite"),
        ("games", "0030_translationsuggestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar"),
                            ("username", "Username"),
                            ("review", "Review"),
                            ("translation_suggestion", "Translation Suggestion"),
                            ("game_list_note", "GameList Note"),
                            ("collection", "Collection"),
                            ("collection_item_note", "Collection Item Note"),
                        ],
                        help_text="What kind of thing this report targets.",
                        max_length=25,
                        verbose_name="target type",
                    ),
                ),
                (
                    "reported_value",
                    models.TextField(
                        blank=True,
                        help_text="A snapshot of the offending text at submission time. Blank for avatar reports.",
                        verbose_name="reported value",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="The reporter's free-text explanation of what's wrong.", verbose_name="reason"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                        default="pending",
                        help_text="The current lifecycle state of this report.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True, verbose_name="submitted at")),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time this report was accepted or rejected.",
                        null=True,
                        verbose_name="reviewed at",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional reason given by the admin when rejecting this report.",
                        max_length=500,
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="The user who filed this report.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        help_text="The user whose content or profile field is being reported.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_against",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who accepted or rejected this report.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_collection",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Collection this report targets, when target_type is collection.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="collections.collection",
                    ),
                ),
                (
                    "target_collection_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The CollectionItem this report targets (its note), when target_type is collection_item_note.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="collections.collectionitem",
                    ),
                ),
                (
                    "target_game_list",
                    models.ForeignKey(
                        blank=True,
                        help_text="The GameList this report targets (its note), when target_type is game_list_note.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="games.gamelist",
                    ),
                ),
                (
                    "target_review",
                    models.ForeignKey(
                        blank=True,
                        help_text="The GameReview this report targets, when target_type is review.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="games.gamereview",
                    ),
                ),
                (
                    "target_translation_suggestion",
                    models.ForeignKey(
                        blank=True,
                        help_text="The TranslationSuggestion this report targets, when target_type is translation_suggestion.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="games.translationsuggestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("reported_by", "target_review"),
                        name="unique_pending_report_per_reporter_review",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("reported_by", "target_translation_suggestion"),
                        name="unique_pending_report_per_reporter_translation_suggestion",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("reported_by", "target_game_list"),
                        name="unique_pending_report_per_reporter_game_list",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("reported_by", "target_collection"),
                        name="unique_pending_report_per_reporter_collection",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("reported_by", "target_collection_item"),
                        name="unique_pending_report_per_reporter_collection_item",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending"), ("target_type", "avatar")),
                        fields=("reported_by", "reported_user", "target_type"),
                        name="unique_pending_avatar_report_per_reporter",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending"), ("target_type", "username")),
                        fields=("reported_by", "reported_user", "target_type"),
                        name="unique_pending_username_report_per_reporter",
                    ),
                ],
            },
        ),
    ]
