# Generated by Django 6.1 on 2026-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0002_warning"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="source",
            field=models.CharField(
                choices=[("user_submitted", "User submitted"), ("admin_direct", "Admin direct")],
                default="user_submitted",
                help_text="Whether this report was filed by an ordinary user, or created by an admin via direct moderation.",
                max_length=20,
                verbose_name="source",
            ),
        ),
    ]
