# Generated by Django 6.0.6 on 2026-07-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_email_alter_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user has accumulated 3 warnings. Distinct from is_active, which gates login.",
                verbose_name="is banned",
            ),
        ),
    ]
