# Generated by Django 6.0.6 on 2026-07-09 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationWarning",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issued_at", models.DateTimeField(auto_now_add=True, verbose_name="issued at")),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="The admin who accepted the report and issued this warning.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_warnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        help_text="The accepted report that caused this warning.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warning",
                        to="moderation.report",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this warning was issued to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "warning",
                "verbose_name_plural": "warnings",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
    ]
